"""
Train a landmark-based sign classifier using extracted MediaPipe keypoints.

Example:
python train_landmark_model.py --dataset_npz landmark_dataset.npz
"""

from __future__ import annotations

import argparse
import json

import numpy as np
import tensorflow as tf
from sklearn.metrics import classification_report
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import BatchNormalization, Dense, Dropout, Input
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dataset_npz",
        default="landmark_dataset.npz",
        help="Path to NPZ file generated by extract_landmarks.py.",
    )
    parser.add_argument(
        "--output_model",
        default="landmark_model.h5",
        help="Output model path.",
    )
    parser.add_argument(
        "--label_map_path",
        default="label_map.json",
        help="Path to save class index -> label mapping.",
    )
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--batch_size", type=int, default=128)
    parser.add_argument("--learning_rate", type=float, default=1e-3)
    parser.add_argument("--patience", type=int, default=8)
    return parser.parse_args()


def build_model(num_classes, learning_rate):
    model = Sequential(
        [
            Input(shape=(63,)),
            Dense(256, activation="relu"),
            BatchNormalization(),
            Dropout(0.35),
            Dense(128, activation="relu"),
            BatchNormalization(),
            Dropout(0.25),
            Dense(64, activation="relu"),
            Dropout(0.2),
            Dense(num_classes, activation="softmax"),
        ]
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def main():
    args = parse_args()

    data = np.load(args.dataset_npz, allow_pickle=True)
    X_train = data["X_train"]
    y_train = data["y_train"]
    X_val = data["X_val"]
    y_val = data["y_val"]
    X_test = data["X_test"]
    y_test = data["y_test"]
    labels = data["labels"].tolist()

    num_classes = len(labels)
    y_train_oh = to_categorical(y_train, num_classes=num_classes)
    y_val_oh = to_categorical(y_val, num_classes=num_classes)
    y_test_oh = to_categorical(y_test, num_classes=num_classes)

    model = build_model(num_classes, args.learning_rate)
    model.summary()

    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=args.patience,
            restore_best_weights=True,
            verbose=1,
        ),
        ModelCheckpoint(
            filepath=args.output_model,
            monitor="val_accuracy",
            save_best_only=True,
            verbose=1,
        ),
    ]

    model.fit(
        X_train,
        y_train_oh,
        validation_data=(X_val, y_val_oh),
        epochs=args.epochs,
        batch_size=args.batch_size,
        callbacks=callbacks,
        verbose=1,
    )

    test_loss, test_acc = model.evaluate(X_test, y_test_oh, verbose=0)
    print(f"\nTest accuracy: {test_acc:.4f}")
    print(f"Test loss: {test_loss:.4f}")

    preds = model.predict(X_test, verbose=0)
    pred_labels = np.argmax(preds, axis=1)
    print("\nClassification report:")
    print(
        classification_report(
            y_test,
            pred_labels,
            labels=list(range(num_classes)),
            target_names=labels,
            zero_division=0,
        )
    )

    with open(args.label_map_path, "w", encoding="utf-8") as file:
        json.dump({idx: label for idx, label in enumerate(labels)}, file, indent=2)
    print(f"Saved label map: {args.label_map_path}")
    print(f"Saved model: {args.output_model}")


if __name__ == "__main__":
    main()
